language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.3
env:
  global:
    secure:
before_install:
  - gem update --system
  - gem update --remote bundler
before_script:
  - git config --global user.name "$(git --no-pager show --no-patch --format='%an')"
  - git config --global user.email "$(git --no-pager show --no-patch --format='%ae')"
script:
  - git clone -b master --depth 1 --quiet https://${TOKEN}@github.com/hrmrzizon/hrmrzizon.github.com.git _site
  - rm -rf _site/*
  - bundle exec jekyll build
after_success:
  - cd _site
  - git add -A
  - git commit -m "Travis updated to $(git rev-parse --short $TRAVIS_COMMIT) at $(date -u +'%Y-%m-%d %H:%M:%S %Z')"
  - git push https://${TOKEN}@github.com/hrmrzizon/hrmrziozn.github.com.git master --quiet
branches:
  only:
    - source
